services:
  my-nginx:
    build: ./nginx
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - my-spring
    volumes:
      - ./nginx/build/dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot:/etc/nginx/certbot
      - /home/pikolo/project_pikolo/images:/usr/share/nginx/html/images
    environment:
      - TZ=Asia/Seoul
    networks:
      - pikolo-network
    restart: always

  my-spring:
    build: ./openJDK
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@my-oracle:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=pikolo
      - SPRING_DATASOURCE_PASSWORD=pikolo
      - TZ=Asia/Seoul
    volumes:
      - ./openJDK/build/app.jar:/app/app.jar
      - /home/pikolo/project_pikolo/images:/app/images
    command: ["java", "-jar", "/app/app.jar"]
    depends_on:
      my-oracle:
        condition: service_healthy
    networks:
      - pikolo-network
    restart: always

  my-oracle:
    image: doctorkirk/oracle-19c
    container_name: my-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCL
      - ORACLE_PWD=1234
      - ORACLE_CHARACTERSET=KO16MSWIN949
      - TZ=Asia/Seoul
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -L sys/1234@ORCL as sysdba | grep -q 'Connected to'"]
      interval: 60s
      timeout: 30s
      retries: 20
      start_period: 600s
    networks:
      - pikolo-network
    restart: always

networks:
  pikolo-network:
    driver: bridge
